version: '3.4'

services:

  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
      - 15672:15672  


  database:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyVerySecurePassword123
    ports:
      - 1433:1433
    
  documentbroker:
    image: ${DOCKER_REGISTRY-}documentbroker
    build:
      context: .
      dockerfile: DocumentBroker/Dockerfile
    links:
       - rabbitmq
       - database 
     

