version: '3.4'

services:
  documentbroker:
    image: ${DOCKER_REGISTRY-}documentbroker
    build:
      context: .
      dockerfile: DocumentBroker/Dockerfile
    links:
       - rabbitmq
       - database 
   
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    ports:
      - 15672:15672  


  database:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password
    ports:
      - 1433:1433


